blueprint:
  name: Generic 0/1 to Yes/No Template Sensor
  description: Create a template sensor that converts 0 or 1 to Yes or No for any sensor
  domain: automation
  input:
    source_entity:
      name: Source Entity
      description: The entity to convert
      selector:
        entity:
          domain: sensor
    output_name:
      name: Output Sensor Name
      description: The name of the output sensor

trigger:
  - platform: state
    entity_id: !input source_entity

variables:
  source_entity: !input source_entity
  output_name: !input output_name

action:
  - service: input_text.set_value
    data:
      entity_id: !input output_name
      value: >
        {% if is_state(source_entity, '1') %}
          Yes
        {% else %}
          No
        {% endif %}
  - platform: template
    sensors:
      "{{ output_name }}":
        friendly_name: "{{ states[source_entity].name }} Yes/No"
        value_template: >
          {% if is_state(source_entity, '1') %}
            Yes
          {% else %}
            No
          {% endif %}
        icon_template: mdi:checkbox-marked-circle-outline
