blueprint:
  name: Generic 0/1 to Yes/No Template Sensor
  description: Create a template sensor that converts 0 or 1 to Yes or No for any sensor
  domain: automation
  input:
    source_entity:
      name: Source Entity
      description: The entity to convert
      selector:
        entity:
          domain: sensor
    output_name:
      name: Output Sensor Name
      description: The name of the output sensor
      default: "output_sensor_yes_no"

trigger:
  - platform: state
    entity_id: !input source_entity

action:
  - service: input_text.set_value
    target:
      entity_id: !input output_name
    data:
      value: >
        {% if is_state(source_entity, '1') %}
          Yes
        {% else %}
          No
        {% endif %}
